### PR TITLE
add: Requirements.txt

### PR DESCRIPTION
**Pull request by FernandaOchoa**
The requirements.txt file simplifies the process of sharing and replicating a project's environment. It allows developers to easily share the list of required packages with others, ensuring that everyone has the same set of dependencies. It also helps in setting up the project on different systems or deployment environments by installing the necessary packages automatically.

### CODE REVIEW

**Comment by Danie1** [comment]
We are using Poetry for dependency management.

The README in your PR includes "Installation" twice.

**Comment by FernandaOchoa** [comment]
Howdy, yes but not all your user's are consider poetry to manage their dependencies. 

I have to install some of them via pip for try to run the sample code. 

I have 2 Installations at readme, considering to install the requirements before to install the library.

**Comment by Danie1** [comment]
Ok, I think I gotcha. 
I find it quite confusing to have 2 "Installation" headers in the README. 
Since you're proposing this to ease the development of threads-api how about I'll add this as another section, as part of "Contributing to threds-api". 

We will need to somehow maintain both requirements.txt and pyproject.toml.. so lets see how it goes.

WDYT?

**Comment by FernandaOchoa** [comment]
Ok, LGTM! 

Let me know if do you need some help to get updated both files.

**Comment by Danie1** [comment]
This will be addressed in https://github.com/Danie1/threads-api/pull/28

Thanks for the suggestion :)

**Pull request closed without merging**
